spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

server:
  port: 8081