spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql://somehostname:someport/databasename
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate